#cloud-config
hostname: rancher01

manage_etc_hosts: true
rancher:
  # environment:
  #   EXTRA_CMDLINE: /init
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 10.20.0.22/24
        gateway: 10.20.0.1
    dns:
      nameservers:
        - 10.20.0.1
  services:
    console:
      environment:
        TZ: Europe/Copenhagen
    rancher-agent1:
      image: rancher/rancher-agent:v2.3.5
      privileged: true
      restart: unless-stopped
      volumes:
        - /etc/kubernetes:/etc/kubernetes
        - /var/run:/var/run
      net: host
      networks:
      hostnet: {}
      external: true
      name: host
      environment:
        - CATTLE_SERVER=https://rancher.do...
        - CATTLE_TOKEN=x54dfvcf7bhjl5bmzrg867bm5r7nn76gwbhmcnt8zttmdz9fqqqjls
        - ETCD=false
        - CONTROL=true
        - WORKER=false
  state:
    dev: LABEL=RANCHER_STATE
    wait: true

chpasswd:
  expire: False
users:
  - default
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwsmDCLBa0oU3JEEvyYG6GhKdaY5ZQvn6T3d4EsIdj8g+oqM1t+MO6zMn1hNbJQU3SUc0WDSzuJHL+nKmImjBiYqYMKUZ3o73bzpKiy94v6+m5L8KNbpf0bEVeletsr5r/2pxI1VEpMH9BHeDPKTTDkaQu1+INsSvNW0FfnwEsxiXilhN8esusv6dISmTtQ9Mko0AbutF6RWntiBPq391PhmtUtJqsC740C+UZZCAyuw9p6kq9MXQaaug+IzMxQ/MKSICMjAp49W0o5Tw9zDK2YOzWlx/Jv/Euiz6YDgv0mZFw+EO8MLIgtmP+uPyTFDysldlEtxWJRZzqECOiOSVBGRKB6RvkH1Uazs0uhz8Dg6i/LnOgCK9eZiaKMsRyeFEJ0QbB/VsgOVCimpXDAWBjk6iEnvZwsRaFpEZZFO5VJ1bpYWv/q0gGyyZQICtkngXjqDWgI27+QEAIacD79Io/JdktpIE0opnWwAbFgsdhAdwmn1SZBWCiJNbVQku6ZN0= mikkel@NHORN-BLADE"
